/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { DIAPriceFeed, DIAPriceFeedInterface } from "../DIAPriceFeed";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "getThePrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b507335b49eddb46dbc33336f3a0410008b7be98d4a3a73ffffffffffffffffffffffffffffffffffffffff1660808173ffffffffffffffffffffffffffffffffffffffff1660601b8152505060805160601c6102726100796000396000605301526102726000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80638c3c9a5514610030575b600080fd5b61003861004e565b60405161004591906101d3565b60405180910390f35b6000807f000000000000000000000000000000000000000000000000000000000000000073ffffffffffffffffffffffffffffffffffffffff1663960384a06040518163ffffffff1660e01b81526004016100a8906101b3565b604080518083038186803b1580156100bf57600080fd5b505afa1580156100d3573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100f79190610128565b506fffffffffffffffffffffffffffffffff1690508091505090565b60008151905061012281610225565b92915050565b6000806040838503121561013b57600080fd5b600061014985828601610113565b925050602061015a85828601610113565b9150509250929050565b60006101716008836101ee565b91507f444146492f5553440000000000000000000000000000000000000000000000006000830152602082019050919050565b6101ad8161021b565b82525050565b600060208201905081810360008301526101cc81610164565b9050919050565b60006020820190506101e860008301846101a4565b92915050565b600082825260208201905092915050565b60006fffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b61022e816101ff565b811461023957600080fd5b5056fea264697066735822122070accbee178b84dc0a732812614f9ff6c83377dd2d9c3213e8c61ac2f036514c64736f6c63430008000033";

export class DIAPriceFeed__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<DIAPriceFeed> {
    return super.deploy(overrides || {}) as Promise<DIAPriceFeed>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): DIAPriceFeed {
    return super.attach(address) as DIAPriceFeed;
  }
  connect(signer: Signer): DIAPriceFeed__factory {
    return super.connect(signer) as DIAPriceFeed__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): DIAPriceFeedInterface {
    return new utils.Interface(_abi) as DIAPriceFeedInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): DIAPriceFeed {
    return new Contract(address, _abi, signerOrProvider) as DIAPriceFeed;
  }
}
