/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  INetworkDemandV2,
  INetworkDemandV2Interface,
} from "../INetworkDemandV2";

const _abi = [
  {
    inputs: [],
    name: "calculateNetworkDemand",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class INetworkDemandV2__factory {
  static readonly abi = _abi;
  static createInterface(): INetworkDemandV2Interface {
    return new utils.Interface(_abi) as INetworkDemandV2Interface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): INetworkDemandV2 {
    return new Contract(address, _abi, signerOrProvider) as INetworkDemandV2;
  }
}
