/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PriceFeeds, PriceFeedsInterface } from "../PriceFeeds";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "aggregator",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [],
    name: "getThePrice",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x60a060405234801561001057600080fd5b5060405161039438038061039483398181016040528101906100329190610084565b8073ffffffffffffffffffffffffffffffffffffffff1660808173ffffffffffffffffffffffffffffffffffffffff1660601b81525050506100f6565b60008151905061007e816100df565b92915050565b60006020828403121561009657600080fd5b60006100a48482850161006f565b91505092915050565b60006100b8826100bf565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6100e8816100ad565b81146100f357600080fd5b50565b60805160601c6102816101136000396000605301526102816000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80638c3c9a5514610030575b600080fd5b61003861004e565b60405161004591906101c1565b60405180910390f35b6000807f000000000000000000000000000000000000000000000000000000000000000073ffffffffffffffffffffffffffffffffffffffff1663feaf968c6040518163ffffffff1660e01b815260040160a06040518083038186803b1580156100b757600080fd5b505afa1580156100cb573d6000803e3d6000fd5b505050506040513d601f19601f820116820180604052508101906100ef919061013b565b5050509150508091505090565b60008151905061010b81610206565b92915050565b6000815190506101208161021d565b92915050565b60008151905061013581610234565b92915050565b600080600080600060a0868803121561015357600080fd5b600061016188828901610126565b9550506020610172888289016100fc565b945050604061018388828901610111565b935050606061019488828901610111565b92505060806101a588828901610126565b9150509295509295909350565b6101bb816101e6565b82525050565b60006020820190506101d660008301846101b2565b92915050565b6000819050919050565b6000819050919050565b600069ffffffffffffffffffff82169050919050565b61020f816101dc565b811461021a57600080fd5b50565b610226816101e6565b811461023157600080fd5b50565b61023d816101f0565b811461024857600080fd5b5056fea2646970667358221220a0420d56f327fa354cce3ce5532c991764e8a5f9e1c6514e5308d94ce954fec364736f6c63430008000033";

export class PriceFeeds__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(
    aggregator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<PriceFeeds> {
    return super.deploy(aggregator, overrides || {}) as Promise<PriceFeeds>;
  }
  getDeployTransaction(
    aggregator: string,
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(aggregator, overrides || {});
  }
  attach(address: string): PriceFeeds {
    return super.attach(address) as PriceFeeds;
  }
  connect(signer: Signer): PriceFeeds__factory {
    return super.connect(signer) as PriceFeeds__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PriceFeedsInterface {
    return new utils.Interface(_abi) as PriceFeedsInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PriceFeeds {
    return new Contract(address, _abi, signerOrProvider) as PriceFeeds;
  }
}
